commands:
  enable: ["/etc/init.d/__SERVICE_NAME__", "enable"]
  restart: ["/etc/init.d/__SERVICE_NAME__", "restart"]
  start: ["/etc/init.d/__SERVICE_NAME__", "start"]

# -- please note that the source path of the service must be:
# "cmd/edge-cd/service-managers/SERVICE_MANAGER_NAME/service"
edgeCDService:
  # -- destination path of the service file
  destinationPath: '/etc/init.d/edge-cd'
